language: java
os: linux
dist: bionic
jdk: openjdk12
jobs:
  include:
    - stage: Build
      if: type = pull_request
      install:
        - bash <(curl -s https://raw.githubusercontent.com/danger/kotlin/master/scripts/install.sh)
        - source ~/.bash_profile
      script:
        - gradle wrapper
        - ./gradlew build
        - ./gradlew shadowJar
        - DEBUG='*' danger-kotlin ci